# Generated by Django 2.1.3 on 2019-11-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluate_models',
            options={'verbose_name': '模型评估', 'verbose_name_plural': '模型评估'},
        ),
        migrations.AlterModelOptions(
            name='released_models',
            options={'verbose_name': '模型发布', 'verbose_name_plural': '模型发布'},
        ),
    ]
