# Generated by Django 2.1.3 on 2019-11-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_auto_20191120_1026'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evaluate_models',
            table='evaluate_models',
        ),
        migrations.AlterModelTable(
            name='released_models',
            table='released_models',
        ),
    ]
