# Generated by Django 2.1.3 on 2019-11-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0003_auto_20191120_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate_models',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='released_models',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
