# Generated by Django 2.1.3 on 2019-11-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='任务ID')),
                ('data_name', models.CharField(max_length=255, verbose_name='数据名称')),
                ('data_type', models.CharField(max_length=100, verbose_name='数据类型')),
                ('images_type', models.CharField(max_length=100, verbose_name='图片类型')),
                ('type', models.CharField(max_length=100, verbose_name='数据类别')),
                ('train', models.CharField(max_length=100, verbose_name='训练集占比')),
                ('val', models.CharField(max_length=100, verbose_name='验证集占比')),
                ('test', models.CharField(max_length=100, verbose_name='测试集占比')),
                ('sour_data', models.TextField(max_length=500, verbose_name='原始数据')),
                ('data_describe', models.TextField(max_length=500, verbose_name='数据描述')),
                ('status', models.CharField(max_length=100, verbose_name='任务状态')),
                ('machine_id', models.CharField(max_length=100, verbose_name='机器ID')),
            ],
            options={
                'verbose_name': '数据',
                'verbose_name_plural': '数据',
                'db_table': 'datas',
            },
        ),
        migrations.CreateModel(
            name='NetworkDescribe',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='任务ID')),
                ('net_name', models.CharField(max_length=255, verbose_name='网络名称')),
                ('src_network', models.TextField(max_length=500, verbose_name='网络目录')),
                ('net_describe', models.TextField(max_length=500, verbose_name='网络描述')),
                ('type', models.CharField(max_length=100, verbose_name='网络类型')),
                ('status', models.CharField(max_length=100, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '网络',
                'verbose_name_plural': '网络',
                'db_table': 'network_describe',
            },
        ),
        migrations.CreateModel(
            name='TrainTask',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='任务名')),
                ('network_path', models.TextField(max_length=500, verbose_name='网络目录')),
                ('task_describe', models.TextField(max_length=500, verbose_name='任务描述')),
                ('image_type', models.CharField(max_length=100, verbose_name='图片类型')),
                ('data_path', models.TextField(max_length=500, verbose_name='数据目录')),
                ('category_num', models.CharField(max_length=100, verbose_name='训练类别')),
                ('iter_num', models.CharField(max_length=100, verbose_name='全量迭代')),
                ('learning_rate', models.CharField(max_length=100, verbose_name='初始学习率')),
                ('batch_size', models.CharField(max_length=100, verbose_name='批大小')),
                ('steps', models.CharField(max_length=100, verbose_name='步长')),
                ('gpus', models.CharField(max_length=100, verbose_name='GPU')),
                ('model', models.CharField(max_length=255, verbose_name='模型目录')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('machine_id', models.CharField(max_length=100, verbose_name='机器ID')),
                ('type', models.CharField(max_length=100, verbose_name='训练类型')),
                ('weights', models.TextField(max_length=500, verbose_name='初始权重文件')),
                ('parallel_bool', models.CharField(default='0', max_length=100, verbose_name='分布式')),
                ('status', models.CharField(max_length=100, verbose_name='训练状态')),
                ('data_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_app.Datas', verbose_name='数据描述')),
                ('net_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_app.NetworkDescribe', verbose_name='网络描述')),
            ],
            options={
                'verbose_name': '训练',
                'verbose_name_plural': '训练',
                'db_table': 'train_task',
            },
        ),
    ]
